version: '3.9'

services:
  api:
    container_name: products-api
    build:
      context: .
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./:/server
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}

volumes:
  postgres_data:
