version: '3.9'

services:
  api:
    container_name: products-api
    build:
      context: .
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}

volumes:
  postgres_data:
