version: '3.9'

services:
  api:
    container_name: products-api
    build:
      context: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./:/service
    depends_on:
      - db

  db:
    build:
      context: ./database
    restart: always
    volumes:
      - ~/Documents/Coding/data:/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
