version: '3.9'

services:
  api:
    container_name: products-api
    build:
      context: .
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - ./:/service
    depends_on:
      - db

  db:
    build:
      context: ./database
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'

volumes:
  pg_data:
