version: '3.9'

services:
  api:
    build:
      context: .
    restart: on-failure
    command: npm start
    # command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./:/service
    depends_on:
      - db

  db:
    build:
      context: ./database
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  pg_data:
