DROP TABLE IF EXISTS products;

CREATE TABLE products (
  product_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  name VARCHAR (255) NOT NULL,
  slogan VARCHAR (255) NOT NULL,
  description TEXT NOT NULL,
  category VARCHAR (255) NOT NULL,
  default_price INTEGER NOT NULL
);

DROP TABLE IF EXISTS features;

CREATE TABLE features (
  features_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  product_id INTEGER REFERENCES products ON DELETE CASCADE,
  feature VARCHAR (255),
  value VARCHAR (255)
);

DROP TABLE IF EXISTS styles;

CREATE TABLE styles (
  styles_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  product_id INTEGER REFERENCES products ON DELETE CASCADE,
  name VARCHAR (255) NOT NULL,
  sale_price INTEGER NOT NULL,
  original_price INTEGER NOT NULL,
  default_style INTEGER
);

DROP TABLE IF EXISTS related;

CREATE TABLE related (
  related_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  product_id INTEGER REFERENCES products ON DELETE CASCADE,
  related_product_id INTEGER
);

DROP TABLE IF EXISTS photos;

CREATE TABLE photos (
  photos_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  styles_id INTEGER,
  url TEXT,
  thumbnail_url TEXT
);

DROP TABLE IF EXISTS skus;

CREATE TABLE skus (
  skus_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  styles_id INTEGER,
  size VARCHAR (50) NOT NULL,
  quantity INTEGER
);